[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
yew-router = "0.16"
stylist = {version = "0.10", features = ["yew"]}
wasm-bindgen ="0.2"
web-sys = {version = "0.3", features = ["HtmlInputElement"]}
gloo ="0.8"

[dev-dependencies]
